/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitudPagoTransporteRouteImport } from './routes/solicitud-pago-transporte'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalEstudianteRouteRouteImport } from './routes/_portal-estudiante/route'
import { Route as PortalRouteRouteImport } from './routes/_portal/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedMiCuentaRouteImport } from './routes/_authenticated/mi-cuenta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal.index'
import { Route as PortalEstudiantePortalEstudianteIndexRouteImport } from './routes/_portal-estudiante/portal-estudiante.index'
import { Route as AuthenticatedTransportesIndexRouteImport } from './routes/_authenticated/transportes.index'
import { Route as AuthenticatedSolicitudesIndexRouteImport } from './routes/_authenticated/solicitudes.index'
import { Route as AuthenticatedPermisosIndexRouteImport } from './routes/_authenticated/permisos.index'
import { Route as AuthenticatedExpedientesIndexRouteImport } from './routes/_authenticated/expedientes.index'
import { Route as ImprimirSolicitudPagoIdRouteImport } from './routes/imprimir/solicitud-pago.$id'
import { Route as ApiPublicSolicitudPagoTransporteRouteImport } from './routes/api/public/solicitud-pago-transporte'
import { Route as ApiPublicCatalogoViajesTransporteRouteImport } from './routes/api/public/catalogo-viajes-transporte'
import { Route as PortalPortalCambiarPasswordRouteImport } from './routes/_portal/portal.cambiar-password'
import { Route as PortalEstudiantePortalEstudianteCambiarPasswordRouteImport } from './routes/_portal-estudiante/portal-estudiante.cambiar-password'
import { Route as AuthenticatedTransportesNuevoRouteImport } from './routes/_authenticated/transportes.nuevo'
import { Route as AuthenticatedTransportesDashboardRouteImport } from './routes/_authenticated/transportes.dashboard'
import { Route as AuthenticatedTransportesIdRouteImport } from './routes/_authenticated/transportes.$id'
import { Route as AuthenticatedSolicitudesOcrRouteImport } from './routes/_authenticated/solicitudes.ocr'
import { Route as AuthenticatedSolicitudesNuevaRouteImport } from './routes/_authenticated/solicitudes.nueva'
import { Route as AuthenticatedSolicitudesIdRouteImport } from './routes/_authenticated/solicitudes.$id'
import { Route as AuthenticatedPermisosNuevoRouteImport } from './routes/_authenticated/permisos.nuevo'
import { Route as AuthenticatedPermisosIdRouteImport } from './routes/_authenticated/permisos.$id'
import { Route as AuthenticatedExpedientesPapeleraRouteImport } from './routes/_authenticated/expedientes.papelera'
import { Route as AuthenticatedExpedientesNuevoRouteImport } from './routes/_authenticated/expedientes.nuevo'
import { Route as AuthenticatedExpedientesDashboardRouteImport } from './routes/_authenticated/expedientes.dashboard'
import { Route as AuthenticatedExpedientesIdRouteImport } from './routes/_authenticated/expedientes.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSolicitudesPagoTransporteRouteImport } from './routes/_authenticated/admin.solicitudes-pago-transporte'
import { Route as AuthenticatedAdminReportesFiscalesRouteImport } from './routes/_authenticated/admin.reportes-fiscales'
import { Route as AuthenticatedAdminGastosOperativosRouteImport } from './routes/_authenticated/admin.gastos-operativos'
import { Route as AuthenticatedAdminFacturacionRouteImport } from './routes/_authenticated/admin.facturacion'
import { Route as AuthenticatedAdminDashboardFinancieroRouteImport } from './routes/_authenticated/admin.dashboard-financiero'
import { Route as AuthenticatedAdminCuentasPorPagarRouteImport } from './routes/_authenticated/admin.cuentas-por-pagar'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminCatalogosRouteImport } from './routes/_authenticated/admin.catalogos'
import { Route as AuthenticatedAdminCatalogoViajesTransporteRouteImport } from './routes/_authenticated/admin.catalogo-viajes-transporte'
import { Route as AuthenticatedAdminAccesosClientesRouteImport } from './routes/_authenticated/admin.accesos-clientes'
import { Route as AuthenticatedAcademiaProgramasRouteImport } from './routes/_authenticated/academia.programas'
import { Route as AuthenticatedAcademiaInscripcionesRouteImport } from './routes/_authenticated/academia.inscripciones'
import { Route as AuthenticatedAcademiaEstudiantesRouteImport } from './routes/_authenticated/academia.estudiantes'
import { Route as AuthenticatedAcademiaAccesosEstudiantesRouteImport } from './routes/_authenticated/academia.accesos-estudiantes'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedRrhhPrestamosIndexRouteImport } from './routes/_authenticated/rrhh.prestamos.index'
import { Route as AuthenticatedRrhhPrestamosTercerosIndexRouteImport } from './routes/_authenticated/rrhh.prestamos-terceros.index'
import { Route as AuthenticatedRrhhEmpleadosIndexRouteImport } from './routes/_authenticated/rrhh.empleados.index'
import { Route as AuthenticatedLegalDocumentosIndexRouteImport } from './routes/_authenticated/legal.documentos.index'
import { Route as ApiPublicSolicitudPagoTransporteIdRouteImport } from './routes/api/public/solicitud-pago-transporte.$id'
import { Route as ApiPublicReciboPagoIdRouteImport } from './routes/api/public/recibo-pago.$id'
import { Route as PortalPortalExpedientesIdRouteImport } from './routes/_portal/portal.expedientes.$id'
import { Route as PortalEstudiantePortalEstudianteProgramasIdRouteImport } from './routes/_portal-estudiante/portal-estudiante.programas.$id'
import { Route as AuthenticatedRrhhEmpleadosIdRouteImport } from './routes/_authenticated/rrhh.empleados.$id'
import { Route as AuthenticatedAdminFacturacionPendientesRouteImport } from './routes/_authenticated/admin.facturacion.pendientes'

const SolicitudPagoTransporteRoute = SolicitudPagoTransporteRouteImport.update({
  id: '/solicitud-pago-transporte',
  path: '/solicitud-pago-transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEstudianteRouteRoute = PortalEstudianteRouteRouteImport.update({
  id: '/_portal-estudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiCuentaRoute = AuthenticatedMiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalEstudiantePortalEstudianteIndexRoute =
  PortalEstudiantePortalEstudianteIndexRouteImport.update({
    id: '/portal-estudiante/',
    path: '/portal-estudiante/',
    getParentRoute: () => PortalEstudianteRouteRoute,
  } as any)
const AuthenticatedTransportesIndexRoute =
  AuthenticatedTransportesIndexRouteImport.update({
    id: '/transportes/',
    path: '/transportes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesIndexRoute =
  AuthenticatedSolicitudesIndexRouteImport.update({
    id: '/solicitudes/',
    path: '/solicitudes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosIndexRoute =
  AuthenticatedPermisosIndexRouteImport.update({
    id: '/permisos/',
    path: '/permisos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesIndexRoute =
  AuthenticatedExpedientesIndexRouteImport.update({
    id: '/expedientes/',
    path: '/expedientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ImprimirSolicitudPagoIdRoute = ImprimirSolicitudPagoIdRouteImport.update({
  id: '/imprimir/solicitud-pago/$id',
  path: '/imprimir/solicitud-pago/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSolicitudPagoTransporteRoute =
  ApiPublicSolicitudPagoTransporteRouteImport.update({
    id: '/api/public/solicitud-pago-transporte',
    path: '/api/public/solicitud-pago-transporte',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogoViajesTransporteRoute =
  ApiPublicCatalogoViajesTransporteRouteImport.update({
    id: '/api/public/catalogo-viajes-transporte',
    path: '/api/public/catalogo-viajes-transporte',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalPortalCambiarPasswordRoute =
  PortalPortalCambiarPasswordRouteImport.update({
    id: '/portal/cambiar-password',
    path: '/portal/cambiar-password',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalEstudiantePortalEstudianteCambiarPasswordRoute =
  PortalEstudiantePortalEstudianteCambiarPasswordRouteImport.update({
    id: '/portal-estudiante/cambiar-password',
    path: '/portal-estudiante/cambiar-password',
    getParentRoute: () => PortalEstudianteRouteRoute,
  } as any)
const AuthenticatedTransportesNuevoRoute =
  AuthenticatedTransportesNuevoRouteImport.update({
    id: '/transportes/nuevo',
    path: '/transportes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportesDashboardRoute =
  AuthenticatedTransportesDashboardRouteImport.update({
    id: '/transportes/dashboard',
    path: '/transportes/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportesIdRoute =
  AuthenticatedTransportesIdRouteImport.update({
    id: '/transportes/$id',
    path: '/transportes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesOcrRoute =
  AuthenticatedSolicitudesOcrRouteImport.update({
    id: '/solicitudes/ocr',
    path: '/solicitudes/ocr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesNuevaRoute =
  AuthenticatedSolicitudesNuevaRouteImport.update({
    id: '/solicitudes/nueva',
    path: '/solicitudes/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesIdRoute =
  AuthenticatedSolicitudesIdRouteImport.update({
    id: '/solicitudes/$id',
    path: '/solicitudes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosNuevoRoute =
  AuthenticatedPermisosNuevoRouteImport.update({
    id: '/permisos/nuevo',
    path: '/permisos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosIdRoute = AuthenticatedPermisosIdRouteImport.update({
  id: '/permisos/$id',
  path: '/permisos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpedientesPapeleraRoute =
  AuthenticatedExpedientesPapeleraRouteImport.update({
    id: '/expedientes/papelera',
    path: '/expedientes/papelera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesNuevoRoute =
  AuthenticatedExpedientesNuevoRouteImport.update({
    id: '/expedientes/nuevo',
    path: '/expedientes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesDashboardRoute =
  AuthenticatedExpedientesDashboardRouteImport.update({
    id: '/expedientes/dashboard',
    path: '/expedientes/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesIdRoute =
  AuthenticatedExpedientesIdRouteImport.update({
    id: '/expedientes/$id',
    path: '/expedientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSolicitudesPagoTransporteRoute =
  AuthenticatedAdminSolicitudesPagoTransporteRouteImport.update({
    id: '/admin/solicitudes-pago-transporte',
    path: '/admin/solicitudes-pago-transporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportesFiscalesRoute =
  AuthenticatedAdminReportesFiscalesRouteImport.update({
    id: '/admin/reportes-fiscales',
    path: '/admin/reportes-fiscales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGastosOperativosRoute =
  AuthenticatedAdminGastosOperativosRouteImport.update({
    id: '/admin/gastos-operativos',
    path: '/admin/gastos-operativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFacturacionRoute =
  AuthenticatedAdminFacturacionRouteImport.update({
    id: '/admin/facturacion',
    path: '/admin/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardFinancieroRoute =
  AuthenticatedAdminDashboardFinancieroRouteImport.update({
    id: '/admin/dashboard-financiero',
    path: '/admin/dashboard-financiero',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCuentasPorPagarRoute =
  AuthenticatedAdminCuentasPorPagarRouteImport.update({
    id: '/admin/cuentas-por-pagar',
    path: '/admin/cuentas-por-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/admin/configuracion',
    path: '/admin/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogosRoute =
  AuthenticatedAdminCatalogosRouteImport.update({
    id: '/admin/catalogos',
    path: '/admin/catalogos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogoViajesTransporteRoute =
  AuthenticatedAdminCatalogoViajesTransporteRouteImport.update({
    id: '/admin/catalogo-viajes-transporte',
    path: '/admin/catalogo-viajes-transporte',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccesosClientesRoute =
  AuthenticatedAdminAccesosClientesRouteImport.update({
    id: '/admin/accesos-clientes',
    path: '/admin/accesos-clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademiaProgramasRoute =
  AuthenticatedAcademiaProgramasRouteImport.update({
    id: '/academia/programas',
    path: '/academia/programas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademiaInscripcionesRoute =
  AuthenticatedAcademiaInscripcionesRouteImport.update({
    id: '/academia/inscripciones',
    path: '/academia/inscripciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademiaEstudiantesRoute =
  AuthenticatedAcademiaEstudiantesRouteImport.update({
    id: '/academia/estudiantes',
    path: '/academia/estudiantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademiaAccesosEstudiantesRoute =
  AuthenticatedAcademiaAccesosEstudiantesRouteImport.update({
    id: '/academia/accesos-estudiantes',
    path: '/academia/accesos-estudiantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRrhhPrestamosIndexRoute =
  AuthenticatedRrhhPrestamosIndexRouteImport.update({
    id: '/rrhh/prestamos/',
    path: '/rrhh/prestamos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRrhhPrestamosTercerosIndexRoute =
  AuthenticatedRrhhPrestamosTercerosIndexRouteImport.update({
    id: '/rrhh/prestamos-terceros/',
    path: '/rrhh/prestamos-terceros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRrhhEmpleadosIndexRoute =
  AuthenticatedRrhhEmpleadosIndexRouteImport.update({
    id: '/rrhh/empleados/',
    path: '/rrhh/empleados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegalDocumentosIndexRoute =
  AuthenticatedLegalDocumentosIndexRouteImport.update({
    id: '/legal/documentos/',
    path: '/legal/documentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSolicitudPagoTransporteIdRoute =
  ApiPublicSolicitudPagoTransporteIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicSolicitudPagoTransporteRoute,
  } as any)
const ApiPublicReciboPagoIdRoute = ApiPublicReciboPagoIdRouteImport.update({
  id: '/api/public/recibo-pago/$id',
  path: '/api/public/recibo-pago/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalExpedientesIdRoute =
  PortalPortalExpedientesIdRouteImport.update({
    id: '/portal/expedientes/$id',
    path: '/portal/expedientes/$id',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalEstudiantePortalEstudianteProgramasIdRoute =
  PortalEstudiantePortalEstudianteProgramasIdRouteImport.update({
    id: '/portal-estudiante/programas/$id',
    path: '/portal-estudiante/programas/$id',
    getParentRoute: () => PortalEstudianteRouteRoute,
  } as any)
const AuthenticatedRrhhEmpleadosIdRoute =
  AuthenticatedRrhhEmpleadosIdRouteImport.update({
    id: '/rrhh/empleados/$id',
    path: '/rrhh/empleados/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFacturacionPendientesRoute =
  AuthenticatedAdminFacturacionPendientesRouteImport.update({
    id: '/pendientes',
    path: '/pendientes',
    getParentRoute: () => AuthenticatedAdminFacturacionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitud-pago-transporte': typeof SolicitudPagoTransporteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/academia/accesos-estudiantes': typeof AuthenticatedAcademiaAccesosEstudiantesRoute
  '/academia/estudiantes': typeof AuthenticatedAcademiaEstudiantesRoute
  '/academia/inscripciones': typeof AuthenticatedAcademiaInscripcionesRoute
  '/academia/programas': typeof AuthenticatedAcademiaProgramasRoute
  '/admin/accesos-clientes': typeof AuthenticatedAdminAccesosClientesRoute
  '/admin/catalogo-viajes-transporte': typeof AuthenticatedAdminCatalogoViajesTransporteRoute
  '/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/cuentas-por-pagar': typeof AuthenticatedAdminCuentasPorPagarRoute
  '/admin/dashboard-financiero': typeof AuthenticatedAdminDashboardFinancieroRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRouteWithChildren
  '/admin/gastos-operativos': typeof AuthenticatedAdminGastosOperativosRoute
  '/admin/reportes-fiscales': typeof AuthenticatedAdminReportesFiscalesRoute
  '/admin/solicitudes-pago-transporte': typeof AuthenticatedAdminSolicitudesPagoTransporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/expedientes/dashboard': typeof AuthenticatedExpedientesDashboardRoute
  '/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/portal-estudiante/cambiar-password': typeof PortalEstudiantePortalEstudianteCambiarPasswordRoute
  '/portal/cambiar-password': typeof PortalPortalCambiarPasswordRoute
  '/api/public/catalogo-viajes-transporte': typeof ApiPublicCatalogoViajesTransporteRoute
  '/api/public/solicitud-pago-transporte': typeof ApiPublicSolicitudPagoTransporteRouteWithChildren
  '/imprimir/solicitud-pago/$id': typeof ImprimirSolicitudPagoIdRoute
  '/expedientes/': typeof AuthenticatedExpedientesIndexRoute
  '/permisos/': typeof AuthenticatedPermisosIndexRoute
  '/solicitudes/': typeof AuthenticatedSolicitudesIndexRoute
  '/transportes/': typeof AuthenticatedTransportesIndexRoute
  '/portal-estudiante/': typeof PortalEstudiantePortalEstudianteIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/admin/facturacion/pendientes': typeof AuthenticatedAdminFacturacionPendientesRoute
  '/rrhh/empleados/$id': typeof AuthenticatedRrhhEmpleadosIdRoute
  '/portal-estudiante/programas/$id': typeof PortalEstudiantePortalEstudianteProgramasIdRoute
  '/portal/expedientes/$id': typeof PortalPortalExpedientesIdRoute
  '/api/public/recibo-pago/$id': typeof ApiPublicReciboPagoIdRoute
  '/api/public/solicitud-pago-transporte/$id': typeof ApiPublicSolicitudPagoTransporteIdRoute
  '/legal/documentos/': typeof AuthenticatedLegalDocumentosIndexRoute
  '/rrhh/empleados/': typeof AuthenticatedRrhhEmpleadosIndexRoute
  '/rrhh/prestamos-terceros/': typeof AuthenticatedRrhhPrestamosTercerosIndexRoute
  '/rrhh/prestamos/': typeof AuthenticatedRrhhPrestamosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitud-pago-transporte': typeof SolicitudPagoTransporteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/academia/accesos-estudiantes': typeof AuthenticatedAcademiaAccesosEstudiantesRoute
  '/academia/estudiantes': typeof AuthenticatedAcademiaEstudiantesRoute
  '/academia/inscripciones': typeof AuthenticatedAcademiaInscripcionesRoute
  '/academia/programas': typeof AuthenticatedAcademiaProgramasRoute
  '/admin/accesos-clientes': typeof AuthenticatedAdminAccesosClientesRoute
  '/admin/catalogo-viajes-transporte': typeof AuthenticatedAdminCatalogoViajesTransporteRoute
  '/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/cuentas-por-pagar': typeof AuthenticatedAdminCuentasPorPagarRoute
  '/admin/dashboard-financiero': typeof AuthenticatedAdminDashboardFinancieroRoute
  '/admin/facturacion': typeof AuthenticatedAdminFacturacionRouteWithChildren
  '/admin/gastos-operativos': typeof AuthenticatedAdminGastosOperativosRoute
  '/admin/reportes-fiscales': typeof AuthenticatedAdminReportesFiscalesRoute
  '/admin/solicitudes-pago-transporte': typeof AuthenticatedAdminSolicitudesPagoTransporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/expedientes/dashboard': typeof AuthenticatedExpedientesDashboardRoute
  '/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/portal-estudiante/cambiar-password': typeof PortalEstudiantePortalEstudianteCambiarPasswordRoute
  '/portal/cambiar-password': typeof PortalPortalCambiarPasswordRoute
  '/api/public/catalogo-viajes-transporte': typeof ApiPublicCatalogoViajesTransporteRoute
  '/api/public/solicitud-pago-transporte': typeof ApiPublicSolicitudPagoTransporteRouteWithChildren
  '/imprimir/solicitud-pago/$id': typeof ImprimirSolicitudPagoIdRoute
  '/expedientes': typeof AuthenticatedExpedientesIndexRoute
  '/permisos': typeof AuthenticatedPermisosIndexRoute
  '/solicitudes': typeof AuthenticatedSolicitudesIndexRoute
  '/transportes': typeof AuthenticatedTransportesIndexRoute
  '/portal-estudiante': typeof PortalEstudiantePortalEstudianteIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/admin/facturacion/pendientes': typeof AuthenticatedAdminFacturacionPendientesRoute
  '/rrhh/empleados/$id': typeof AuthenticatedRrhhEmpleadosIdRoute
  '/portal-estudiante/programas/$id': typeof PortalEstudiantePortalEstudianteProgramasIdRoute
  '/portal/expedientes/$id': typeof PortalPortalExpedientesIdRoute
  '/api/public/recibo-pago/$id': typeof ApiPublicReciboPagoIdRoute
  '/api/public/solicitud-pago-transporte/$id': typeof ApiPublicSolicitudPagoTransporteIdRoute
  '/legal/documentos': typeof AuthenticatedLegalDocumentosIndexRoute
  '/rrhh/empleados': typeof AuthenticatedRrhhEmpleadosIndexRoute
  '/rrhh/prestamos-terceros': typeof AuthenticatedRrhhPrestamosTercerosIndexRoute
  '/rrhh/prestamos': typeof AuthenticatedRrhhPrestamosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_portal': typeof PortalRouteRouteWithChildren
  '/_portal-estudiante': typeof PortalEstudianteRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/solicitud-pago-transporte': typeof SolicitudPagoTransporteRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mi-cuenta': typeof AuthenticatedMiCuentaRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/academia/accesos-estudiantes': typeof AuthenticatedAcademiaAccesosEstudiantesRoute
  '/_authenticated/academia/estudiantes': typeof AuthenticatedAcademiaEstudiantesRoute
  '/_authenticated/academia/inscripciones': typeof AuthenticatedAcademiaInscripcionesRoute
  '/_authenticated/academia/programas': typeof AuthenticatedAcademiaProgramasRoute
  '/_authenticated/admin/accesos-clientes': typeof AuthenticatedAdminAccesosClientesRoute
  '/_authenticated/admin/catalogo-viajes-transporte': typeof AuthenticatedAdminCatalogoViajesTransporteRoute
  '/_authenticated/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/cuentas-por-pagar': typeof AuthenticatedAdminCuentasPorPagarRoute
  '/_authenticated/admin/dashboard-financiero': typeof AuthenticatedAdminDashboardFinancieroRoute
  '/_authenticated/admin/facturacion': typeof AuthenticatedAdminFacturacionRouteWithChildren
  '/_authenticated/admin/gastos-operativos': typeof AuthenticatedAdminGastosOperativosRoute
  '/_authenticated/admin/reportes-fiscales': typeof AuthenticatedAdminReportesFiscalesRoute
  '/_authenticated/admin/solicitudes-pago-transporte': typeof AuthenticatedAdminSolicitudesPagoTransporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/_authenticated/expedientes/dashboard': typeof AuthenticatedExpedientesDashboardRoute
  '/_authenticated/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/_authenticated/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/_authenticated/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/_authenticated/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/_authenticated/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/_authenticated/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/_authenticated/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/_authenticated/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/_authenticated/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/_authenticated/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/_portal-estudiante/portal-estudiante/cambiar-password': typeof PortalEstudiantePortalEstudianteCambiarPasswordRoute
  '/_portal/portal/cambiar-password': typeof PortalPortalCambiarPasswordRoute
  '/api/public/catalogo-viajes-transporte': typeof ApiPublicCatalogoViajesTransporteRoute
  '/api/public/solicitud-pago-transporte': typeof ApiPublicSolicitudPagoTransporteRouteWithChildren
  '/imprimir/solicitud-pago/$id': typeof ImprimirSolicitudPagoIdRoute
  '/_authenticated/expedientes/': typeof AuthenticatedExpedientesIndexRoute
  '/_authenticated/permisos/': typeof AuthenticatedPermisosIndexRoute
  '/_authenticated/solicitudes/': typeof AuthenticatedSolicitudesIndexRoute
  '/_authenticated/transportes/': typeof AuthenticatedTransportesIndexRoute
  '/_portal-estudiante/portal-estudiante/': typeof PortalEstudiantePortalEstudianteIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_authenticated/admin/facturacion/pendientes': typeof AuthenticatedAdminFacturacionPendientesRoute
  '/_authenticated/rrhh/empleados/$id': typeof AuthenticatedRrhhEmpleadosIdRoute
  '/_portal-estudiante/portal-estudiante/programas/$id': typeof PortalEstudiantePortalEstudianteProgramasIdRoute
  '/_portal/portal/expedientes/$id': typeof PortalPortalExpedientesIdRoute
  '/api/public/recibo-pago/$id': typeof ApiPublicReciboPagoIdRoute
  '/api/public/solicitud-pago-transporte/$id': typeof ApiPublicSolicitudPagoTransporteIdRoute
  '/_authenticated/legal/documentos/': typeof AuthenticatedLegalDocumentosIndexRoute
  '/_authenticated/rrhh/empleados/': typeof AuthenticatedRrhhEmpleadosIndexRoute
  '/_authenticated/rrhh/prestamos-terceros/': typeof AuthenticatedRrhhPrestamosTercerosIndexRoute
  '/_authenticated/rrhh/prestamos/': typeof AuthenticatedRrhhPrestamosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/solicitud-pago-transporte'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes'
    | '/copiloto'
    | '/dashboard'
    | '/mi-cuenta'
    | '/reportes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/academia/accesos-estudiantes'
    | '/academia/estudiantes'
    | '/academia/inscripciones'
    | '/academia/programas'
    | '/admin/accesos-clientes'
    | '/admin/catalogo-viajes-transporte'
    | '/admin/catalogos'
    | '/admin/configuracion'
    | '/admin/cuentas-por-pagar'
    | '/admin/dashboard-financiero'
    | '/admin/facturacion'
    | '/admin/gastos-operativos'
    | '/admin/reportes-fiscales'
    | '/admin/solicitudes-pago-transporte'
    | '/admin/usuarios'
    | '/expedientes/$id'
    | '/expedientes/dashboard'
    | '/expedientes/nuevo'
    | '/expedientes/papelera'
    | '/permisos/$id'
    | '/permisos/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes/ocr'
    | '/transportes/$id'
    | '/transportes/dashboard'
    | '/transportes/nuevo'
    | '/portal-estudiante/cambiar-password'
    | '/portal/cambiar-password'
    | '/api/public/catalogo-viajes-transporte'
    | '/api/public/solicitud-pago-transporte'
    | '/imprimir/solicitud-pago/$id'
    | '/expedientes/'
    | '/permisos/'
    | '/solicitudes/'
    | '/transportes/'
    | '/portal-estudiante/'
    | '/portal/'
    | '/admin/facturacion/pendientes'
    | '/rrhh/empleados/$id'
    | '/portal-estudiante/programas/$id'
    | '/portal/expedientes/$id'
    | '/api/public/recibo-pago/$id'
    | '/api/public/solicitud-pago-transporte/$id'
    | '/legal/documentos/'
    | '/rrhh/empleados/'
    | '/rrhh/prestamos-terceros/'
    | '/rrhh/prestamos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/solicitud-pago-transporte'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes'
    | '/copiloto'
    | '/dashboard'
    | '/mi-cuenta'
    | '/reportes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/academia/accesos-estudiantes'
    | '/academia/estudiantes'
    | '/academia/inscripciones'
    | '/academia/programas'
    | '/admin/accesos-clientes'
    | '/admin/catalogo-viajes-transporte'
    | '/admin/catalogos'
    | '/admin/configuracion'
    | '/admin/cuentas-por-pagar'
    | '/admin/dashboard-financiero'
    | '/admin/facturacion'
    | '/admin/gastos-operativos'
    | '/admin/reportes-fiscales'
    | '/admin/solicitudes-pago-transporte'
    | '/admin/usuarios'
    | '/expedientes/$id'
    | '/expedientes/dashboard'
    | '/expedientes/nuevo'
    | '/expedientes/papelera'
    | '/permisos/$id'
    | '/permisos/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes/ocr'
    | '/transportes/$id'
    | '/transportes/dashboard'
    | '/transportes/nuevo'
    | '/portal-estudiante/cambiar-password'
    | '/portal/cambiar-password'
    | '/api/public/catalogo-viajes-transporte'
    | '/api/public/solicitud-pago-transporte'
    | '/imprimir/solicitud-pago/$id'
    | '/expedientes'
    | '/permisos'
    | '/solicitudes'
    | '/transportes'
    | '/portal-estudiante'
    | '/portal'
    | '/admin/facturacion/pendientes'
    | '/rrhh/empleados/$id'
    | '/portal-estudiante/programas/$id'
    | '/portal/expedientes/$id'
    | '/api/public/recibo-pago/$id'
    | '/api/public/solicitud-pago-transporte/$id'
    | '/legal/documentos'
    | '/rrhh/empleados'
    | '/rrhh/prestamos-terceros'
    | '/rrhh/prestamos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_portal'
    | '/_portal-estudiante'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/solicitud-pago-transporte'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/clientes'
    | '/_authenticated/copiloto'
    | '/_authenticated/dashboard'
    | '/_authenticated/mi-cuenta'
    | '/_authenticated/reportes'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/academia/accesos-estudiantes'
    | '/_authenticated/academia/estudiantes'
    | '/_authenticated/academia/inscripciones'
    | '/_authenticated/academia/programas'
    | '/_authenticated/admin/accesos-clientes'
    | '/_authenticated/admin/catalogo-viajes-transporte'
    | '/_authenticated/admin/catalogos'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/cuentas-por-pagar'
    | '/_authenticated/admin/dashboard-financiero'
    | '/_authenticated/admin/facturacion'
    | '/_authenticated/admin/gastos-operativos'
    | '/_authenticated/admin/reportes-fiscales'
    | '/_authenticated/admin/solicitudes-pago-transporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/expedientes/$id'
    | '/_authenticated/expedientes/dashboard'
    | '/_authenticated/expedientes/nuevo'
    | '/_authenticated/expedientes/papelera'
    | '/_authenticated/permisos/$id'
    | '/_authenticated/permisos/nuevo'
    | '/_authenticated/solicitudes/$id'
    | '/_authenticated/solicitudes/nueva'
    | '/_authenticated/solicitudes/ocr'
    | '/_authenticated/transportes/$id'
    | '/_authenticated/transportes/dashboard'
    | '/_authenticated/transportes/nuevo'
    | '/_portal-estudiante/portal-estudiante/cambiar-password'
    | '/_portal/portal/cambiar-password'
    | '/api/public/catalogo-viajes-transporte'
    | '/api/public/solicitud-pago-transporte'
    | '/imprimir/solicitud-pago/$id'
    | '/_authenticated/expedientes/'
    | '/_authenticated/permisos/'
    | '/_authenticated/solicitudes/'
    | '/_authenticated/transportes/'
    | '/_portal-estudiante/portal-estudiante/'
    | '/_portal/portal/'
    | '/_authenticated/admin/facturacion/pendientes'
    | '/_authenticated/rrhh/empleados/$id'
    | '/_portal-estudiante/portal-estudiante/programas/$id'
    | '/_portal/portal/expedientes/$id'
    | '/api/public/recibo-pago/$id'
    | '/api/public/solicitud-pago-transporte/$id'
    | '/_authenticated/legal/documentos/'
    | '/_authenticated/rrhh/empleados/'
    | '/_authenticated/rrhh/prestamos-terceros/'
    | '/_authenticated/rrhh/prestamos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  PortalEstudianteRouteRoute: typeof PortalEstudianteRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SolicitudPagoTransporteRoute: typeof SolicitudPagoTransporteRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCatalogoViajesTransporteRoute: typeof ApiPublicCatalogoViajesTransporteRoute
  ApiPublicSolicitudPagoTransporteRoute: typeof ApiPublicSolicitudPagoTransporteRouteWithChildren
  ImprimirSolicitudPagoIdRoute: typeof ImprimirSolicitudPagoIdRoute
  ApiPublicReciboPagoIdRoute: typeof ApiPublicReciboPagoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitud-pago-transporte': {
      id: '/solicitud-pago-transporte'
      path: '/solicitud-pago-transporte'
      fullPath: '/solicitud-pago-transporte'
      preLoaderRoute: typeof SolicitudPagoTransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal-estudiante': {
      id: '/_portal-estudiante'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalEstudianteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-cuenta': {
      id: '/_authenticated/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof AuthenticatedMiCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal-estudiante/portal-estudiante/': {
      id: '/_portal-estudiante/portal-estudiante/'
      path: '/portal-estudiante'
      fullPath: '/portal-estudiante/'
      preLoaderRoute: typeof PortalEstudiantePortalEstudianteIndexRouteImport
      parentRoute: typeof PortalEstudianteRouteRoute
    }
    '/_authenticated/transportes/': {
      id: '/_authenticated/transportes/'
      path: '/transportes'
      fullPath: '/transportes/'
      preLoaderRoute: typeof AuthenticatedTransportesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/': {
      id: '/_authenticated/solicitudes/'
      path: '/solicitudes'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof AuthenticatedSolicitudesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/': {
      id: '/_authenticated/permisos/'
      path: '/permisos'
      fullPath: '/permisos/'
      preLoaderRoute: typeof AuthenticatedPermisosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/': {
      id: '/_authenticated/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof AuthenticatedExpedientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/imprimir/solicitud-pago/$id': {
      id: '/imprimir/solicitud-pago/$id'
      path: '/imprimir/solicitud-pago/$id'
      fullPath: '/imprimir/solicitud-pago/$id'
      preLoaderRoute: typeof ImprimirSolicitudPagoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/solicitud-pago-transporte': {
      id: '/api/public/solicitud-pago-transporte'
      path: '/api/public/solicitud-pago-transporte'
      fullPath: '/api/public/solicitud-pago-transporte'
      preLoaderRoute: typeof ApiPublicSolicitudPagoTransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalogo-viajes-transporte': {
      id: '/api/public/catalogo-viajes-transporte'
      path: '/api/public/catalogo-viajes-transporte'
      fullPath: '/api/public/catalogo-viajes-transporte'
      preLoaderRoute: typeof ApiPublicCatalogoViajesTransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/cambiar-password': {
      id: '/_portal/portal/cambiar-password'
      path: '/portal/cambiar-password'
      fullPath: '/portal/cambiar-password'
      preLoaderRoute: typeof PortalPortalCambiarPasswordRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal-estudiante/portal-estudiante/cambiar-password': {
      id: '/_portal-estudiante/portal-estudiante/cambiar-password'
      path: '/portal-estudiante/cambiar-password'
      fullPath: '/portal-estudiante/cambiar-password'
      preLoaderRoute: typeof PortalEstudiantePortalEstudianteCambiarPasswordRouteImport
      parentRoute: typeof PortalEstudianteRouteRoute
    }
    '/_authenticated/transportes/nuevo': {
      id: '/_authenticated/transportes/nuevo'
      path: '/transportes/nuevo'
      fullPath: '/transportes/nuevo'
      preLoaderRoute: typeof AuthenticatedTransportesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/dashboard': {
      id: '/_authenticated/transportes/dashboard'
      path: '/transportes/dashboard'
      fullPath: '/transportes/dashboard'
      preLoaderRoute: typeof AuthenticatedTransportesDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/$id': {
      id: '/_authenticated/transportes/$id'
      path: '/transportes/$id'
      fullPath: '/transportes/$id'
      preLoaderRoute: typeof AuthenticatedTransportesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/ocr': {
      id: '/_authenticated/solicitudes/ocr'
      path: '/solicitudes/ocr'
      fullPath: '/solicitudes/ocr'
      preLoaderRoute: typeof AuthenticatedSolicitudesOcrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/nueva': {
      id: '/_authenticated/solicitudes/nueva'
      path: '/solicitudes/nueva'
      fullPath: '/solicitudes/nueva'
      preLoaderRoute: typeof AuthenticatedSolicitudesNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/$id': {
      id: '/_authenticated/solicitudes/$id'
      path: '/solicitudes/$id'
      fullPath: '/solicitudes/$id'
      preLoaderRoute: typeof AuthenticatedSolicitudesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/nuevo': {
      id: '/_authenticated/permisos/nuevo'
      path: '/permisos/nuevo'
      fullPath: '/permisos/nuevo'
      preLoaderRoute: typeof AuthenticatedPermisosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/$id': {
      id: '/_authenticated/permisos/$id'
      path: '/permisos/$id'
      fullPath: '/permisos/$id'
      preLoaderRoute: typeof AuthenticatedPermisosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/papelera': {
      id: '/_authenticated/expedientes/papelera'
      path: '/expedientes/papelera'
      fullPath: '/expedientes/papelera'
      preLoaderRoute: typeof AuthenticatedExpedientesPapeleraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/nuevo': {
      id: '/_authenticated/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof AuthenticatedExpedientesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/dashboard': {
      id: '/_authenticated/expedientes/dashboard'
      path: '/expedientes/dashboard'
      fullPath: '/expedientes/dashboard'
      preLoaderRoute: typeof AuthenticatedExpedientesDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/$id': {
      id: '/_authenticated/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof AuthenticatedExpedientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/solicitudes-pago-transporte': {
      id: '/_authenticated/admin/solicitudes-pago-transporte'
      path: '/admin/solicitudes-pago-transporte'
      fullPath: '/admin/solicitudes-pago-transporte'
      preLoaderRoute: typeof AuthenticatedAdminSolicitudesPagoTransporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reportes-fiscales': {
      id: '/_authenticated/admin/reportes-fiscales'
      path: '/admin/reportes-fiscales'
      fullPath: '/admin/reportes-fiscales'
      preLoaderRoute: typeof AuthenticatedAdminReportesFiscalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gastos-operativos': {
      id: '/_authenticated/admin/gastos-operativos'
      path: '/admin/gastos-operativos'
      fullPath: '/admin/gastos-operativos'
      preLoaderRoute: typeof AuthenticatedAdminGastosOperativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/facturacion': {
      id: '/_authenticated/admin/facturacion'
      path: '/admin/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard-financiero': {
      id: '/_authenticated/admin/dashboard-financiero'
      path: '/admin/dashboard-financiero'
      fullPath: '/admin/dashboard-financiero'
      preLoaderRoute: typeof AuthenticatedAdminDashboardFinancieroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cuentas-por-pagar': {
      id: '/_authenticated/admin/cuentas-por-pagar'
      path: '/admin/cuentas-por-pagar'
      fullPath: '/admin/cuentas-por-pagar'
      preLoaderRoute: typeof AuthenticatedAdminCuentasPorPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogos': {
      id: '/_authenticated/admin/catalogos'
      path: '/admin/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AuthenticatedAdminCatalogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogo-viajes-transporte': {
      id: '/_authenticated/admin/catalogo-viajes-transporte'
      path: '/admin/catalogo-viajes-transporte'
      fullPath: '/admin/catalogo-viajes-transporte'
      preLoaderRoute: typeof AuthenticatedAdminCatalogoViajesTransporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/accesos-clientes': {
      id: '/_authenticated/admin/accesos-clientes'
      path: '/admin/accesos-clientes'
      fullPath: '/admin/accesos-clientes'
      preLoaderRoute: typeof AuthenticatedAdminAccesosClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academia/programas': {
      id: '/_authenticated/academia/programas'
      path: '/academia/programas'
      fullPath: '/academia/programas'
      preLoaderRoute: typeof AuthenticatedAcademiaProgramasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academia/inscripciones': {
      id: '/_authenticated/academia/inscripciones'
      path: '/academia/inscripciones'
      fullPath: '/academia/inscripciones'
      preLoaderRoute: typeof AuthenticatedAcademiaInscripcionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academia/estudiantes': {
      id: '/_authenticated/academia/estudiantes'
      path: '/academia/estudiantes'
      fullPath: '/academia/estudiantes'
      preLoaderRoute: typeof AuthenticatedAcademiaEstudiantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academia/accesos-estudiantes': {
      id: '/_authenticated/academia/accesos-estudiantes'
      path: '/academia/accesos-estudiantes'
      fullPath: '/academia/accesos-estudiantes'
      preLoaderRoute: typeof AuthenticatedAcademiaAccesosEstudiantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rrhh/prestamos/': {
      id: '/_authenticated/rrhh/prestamos/'
      path: '/rrhh/prestamos'
      fullPath: '/rrhh/prestamos/'
      preLoaderRoute: typeof AuthenticatedRrhhPrestamosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rrhh/prestamos-terceros/': {
      id: '/_authenticated/rrhh/prestamos-terceros/'
      path: '/rrhh/prestamos-terceros'
      fullPath: '/rrhh/prestamos-terceros/'
      preLoaderRoute: typeof AuthenticatedRrhhPrestamosTercerosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rrhh/empleados/': {
      id: '/_authenticated/rrhh/empleados/'
      path: '/rrhh/empleados'
      fullPath: '/rrhh/empleados/'
      preLoaderRoute: typeof AuthenticatedRrhhEmpleadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal/documentos/': {
      id: '/_authenticated/legal/documentos/'
      path: '/legal/documentos'
      fullPath: '/legal/documentos/'
      preLoaderRoute: typeof AuthenticatedLegalDocumentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/solicitud-pago-transporte/$id': {
      id: '/api/public/solicitud-pago-transporte/$id'
      path: '/$id'
      fullPath: '/api/public/solicitud-pago-transporte/$id'
      preLoaderRoute: typeof ApiPublicSolicitudPagoTransporteIdRouteImport
      parentRoute: typeof ApiPublicSolicitudPagoTransporteRoute
    }
    '/api/public/recibo-pago/$id': {
      id: '/api/public/recibo-pago/$id'
      path: '/api/public/recibo-pago/$id'
      fullPath: '/api/public/recibo-pago/$id'
      preLoaderRoute: typeof ApiPublicReciboPagoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/portal/expedientes/$id': {
      id: '/_portal/portal/expedientes/$id'
      path: '/portal/expedientes/$id'
      fullPath: '/portal/expedientes/$id'
      preLoaderRoute: typeof PortalPortalExpedientesIdRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/_portal-estudiante/portal-estudiante/programas/$id': {
      id: '/_portal-estudiante/portal-estudiante/programas/$id'
      path: '/portal-estudiante/programas/$id'
      fullPath: '/portal-estudiante/programas/$id'
      preLoaderRoute: typeof PortalEstudiantePortalEstudianteProgramasIdRouteImport
      parentRoute: typeof PortalEstudianteRouteRoute
    }
    '/_authenticated/rrhh/empleados/$id': {
      id: '/_authenticated/rrhh/empleados/$id'
      path: '/rrhh/empleados/$id'
      fullPath: '/rrhh/empleados/$id'
      preLoaderRoute: typeof AuthenticatedRrhhEmpleadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/facturacion/pendientes': {
      id: '/_authenticated/admin/facturacion/pendientes'
      path: '/pendientes'
      fullPath: '/admin/facturacion/pendientes'
      preLoaderRoute: typeof AuthenticatedAdminFacturacionPendientesRouteImport
      parentRoute: typeof AuthenticatedAdminFacturacionRoute
    }
  }
}

interface AuthenticatedAdminFacturacionRouteChildren {
  AuthenticatedAdminFacturacionPendientesRoute: typeof AuthenticatedAdminFacturacionPendientesRoute
}

const AuthenticatedAdminFacturacionRouteChildren: AuthenticatedAdminFacturacionRouteChildren =
  {
    AuthenticatedAdminFacturacionPendientesRoute:
      AuthenticatedAdminFacturacionPendientesRoute,
  }

const AuthenticatedAdminFacturacionRouteWithChildren =
  AuthenticatedAdminFacturacionRoute._addFileChildren(
    AuthenticatedAdminFacturacionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMiCuentaRoute: typeof AuthenticatedMiCuentaRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedAcademiaAccesosEstudiantesRoute: typeof AuthenticatedAcademiaAccesosEstudiantesRoute
  AuthenticatedAcademiaEstudiantesRoute: typeof AuthenticatedAcademiaEstudiantesRoute
  AuthenticatedAcademiaInscripcionesRoute: typeof AuthenticatedAcademiaInscripcionesRoute
  AuthenticatedAcademiaProgramasRoute: typeof AuthenticatedAcademiaProgramasRoute
  AuthenticatedAdminAccesosClientesRoute: typeof AuthenticatedAdminAccesosClientesRoute
  AuthenticatedAdminCatalogoViajesTransporteRoute: typeof AuthenticatedAdminCatalogoViajesTransporteRoute
  AuthenticatedAdminCatalogosRoute: typeof AuthenticatedAdminCatalogosRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminCuentasPorPagarRoute: typeof AuthenticatedAdminCuentasPorPagarRoute
  AuthenticatedAdminDashboardFinancieroRoute: typeof AuthenticatedAdminDashboardFinancieroRoute
  AuthenticatedAdminFacturacionRoute: typeof AuthenticatedAdminFacturacionRouteWithChildren
  AuthenticatedAdminGastosOperativosRoute: typeof AuthenticatedAdminGastosOperativosRoute
  AuthenticatedAdminReportesFiscalesRoute: typeof AuthenticatedAdminReportesFiscalesRoute
  AuthenticatedAdminSolicitudesPagoTransporteRoute: typeof AuthenticatedAdminSolicitudesPagoTransporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedExpedientesIdRoute: typeof AuthenticatedExpedientesIdRoute
  AuthenticatedExpedientesDashboardRoute: typeof AuthenticatedExpedientesDashboardRoute
  AuthenticatedExpedientesNuevoRoute: typeof AuthenticatedExpedientesNuevoRoute
  AuthenticatedExpedientesPapeleraRoute: typeof AuthenticatedExpedientesPapeleraRoute
  AuthenticatedPermisosIdRoute: typeof AuthenticatedPermisosIdRoute
  AuthenticatedPermisosNuevoRoute: typeof AuthenticatedPermisosNuevoRoute
  AuthenticatedSolicitudesIdRoute: typeof AuthenticatedSolicitudesIdRoute
  AuthenticatedSolicitudesNuevaRoute: typeof AuthenticatedSolicitudesNuevaRoute
  AuthenticatedSolicitudesOcrRoute: typeof AuthenticatedSolicitudesOcrRoute
  AuthenticatedTransportesIdRoute: typeof AuthenticatedTransportesIdRoute
  AuthenticatedTransportesDashboardRoute: typeof AuthenticatedTransportesDashboardRoute
  AuthenticatedTransportesNuevoRoute: typeof AuthenticatedTransportesNuevoRoute
  AuthenticatedExpedientesIndexRoute: typeof AuthenticatedExpedientesIndexRoute
  AuthenticatedPermisosIndexRoute: typeof AuthenticatedPermisosIndexRoute
  AuthenticatedSolicitudesIndexRoute: typeof AuthenticatedSolicitudesIndexRoute
  AuthenticatedTransportesIndexRoute: typeof AuthenticatedTransportesIndexRoute
  AuthenticatedRrhhEmpleadosIdRoute: typeof AuthenticatedRrhhEmpleadosIdRoute
  AuthenticatedLegalDocumentosIndexRoute: typeof AuthenticatedLegalDocumentosIndexRoute
  AuthenticatedRrhhEmpleadosIndexRoute: typeof AuthenticatedRrhhEmpleadosIndexRoute
  AuthenticatedRrhhPrestamosTercerosIndexRoute: typeof AuthenticatedRrhhPrestamosTercerosIndexRoute
  AuthenticatedRrhhPrestamosIndexRoute: typeof AuthenticatedRrhhPrestamosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMiCuentaRoute: AuthenticatedMiCuentaRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedAcademiaAccesosEstudiantesRoute:
    AuthenticatedAcademiaAccesosEstudiantesRoute,
  AuthenticatedAcademiaEstudiantesRoute: AuthenticatedAcademiaEstudiantesRoute,
  AuthenticatedAcademiaInscripcionesRoute:
    AuthenticatedAcademiaInscripcionesRoute,
  AuthenticatedAcademiaProgramasRoute: AuthenticatedAcademiaProgramasRoute,
  AuthenticatedAdminAccesosClientesRoute:
    AuthenticatedAdminAccesosClientesRoute,
  AuthenticatedAdminCatalogoViajesTransporteRoute:
    AuthenticatedAdminCatalogoViajesTransporteRoute,
  AuthenticatedAdminCatalogosRoute: AuthenticatedAdminCatalogosRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminCuentasPorPagarRoute:
    AuthenticatedAdminCuentasPorPagarRoute,
  AuthenticatedAdminDashboardFinancieroRoute:
    AuthenticatedAdminDashboardFinancieroRoute,
  AuthenticatedAdminFacturacionRoute:
    AuthenticatedAdminFacturacionRouteWithChildren,
  AuthenticatedAdminGastosOperativosRoute:
    AuthenticatedAdminGastosOperativosRoute,
  AuthenticatedAdminReportesFiscalesRoute:
    AuthenticatedAdminReportesFiscalesRoute,
  AuthenticatedAdminSolicitudesPagoTransporteRoute:
    AuthenticatedAdminSolicitudesPagoTransporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedExpedientesIdRoute: AuthenticatedExpedientesIdRoute,
  AuthenticatedExpedientesDashboardRoute:
    AuthenticatedExpedientesDashboardRoute,
  AuthenticatedExpedientesNuevoRoute: AuthenticatedExpedientesNuevoRoute,
  AuthenticatedExpedientesPapeleraRoute: AuthenticatedExpedientesPapeleraRoute,
  AuthenticatedPermisosIdRoute: AuthenticatedPermisosIdRoute,
  AuthenticatedPermisosNuevoRoute: AuthenticatedPermisosNuevoRoute,
  AuthenticatedSolicitudesIdRoute: AuthenticatedSolicitudesIdRoute,
  AuthenticatedSolicitudesNuevaRoute: AuthenticatedSolicitudesNuevaRoute,
  AuthenticatedSolicitudesOcrRoute: AuthenticatedSolicitudesOcrRoute,
  AuthenticatedTransportesIdRoute: AuthenticatedTransportesIdRoute,
  AuthenticatedTransportesDashboardRoute:
    AuthenticatedTransportesDashboardRoute,
  AuthenticatedTransportesNuevoRoute: AuthenticatedTransportesNuevoRoute,
  AuthenticatedExpedientesIndexRoute: AuthenticatedExpedientesIndexRoute,
  AuthenticatedPermisosIndexRoute: AuthenticatedPermisosIndexRoute,
  AuthenticatedSolicitudesIndexRoute: AuthenticatedSolicitudesIndexRoute,
  AuthenticatedTransportesIndexRoute: AuthenticatedTransportesIndexRoute,
  AuthenticatedRrhhEmpleadosIdRoute: AuthenticatedRrhhEmpleadosIdRoute,
  AuthenticatedLegalDocumentosIndexRoute:
    AuthenticatedLegalDocumentosIndexRoute,
  AuthenticatedRrhhEmpleadosIndexRoute: AuthenticatedRrhhEmpleadosIndexRoute,
  AuthenticatedRrhhPrestamosTercerosIndexRoute:
    AuthenticatedRrhhPrestamosTercerosIndexRoute,
  AuthenticatedRrhhPrestamosIndexRoute: AuthenticatedRrhhPrestamosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalRouteRouteChildren {
  PortalPortalCambiarPasswordRoute: typeof PortalPortalCambiarPasswordRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
  PortalPortalExpedientesIdRoute: typeof PortalPortalExpedientesIdRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalPortalCambiarPasswordRoute: PortalPortalCambiarPasswordRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
  PortalPortalExpedientesIdRoute: PortalPortalExpedientesIdRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

interface PortalEstudianteRouteRouteChildren {
  PortalEstudiantePortalEstudianteCambiarPasswordRoute: typeof PortalEstudiantePortalEstudianteCambiarPasswordRoute
  PortalEstudiantePortalEstudianteIndexRoute: typeof PortalEstudiantePortalEstudianteIndexRoute
  PortalEstudiantePortalEstudianteProgramasIdRoute: typeof PortalEstudiantePortalEstudianteProgramasIdRoute
}

const PortalEstudianteRouteRouteChildren: PortalEstudianteRouteRouteChildren = {
  PortalEstudiantePortalEstudianteCambiarPasswordRoute:
    PortalEstudiantePortalEstudianteCambiarPasswordRoute,
  PortalEstudiantePortalEstudianteIndexRoute:
    PortalEstudiantePortalEstudianteIndexRoute,
  PortalEstudiantePortalEstudianteProgramasIdRoute:
    PortalEstudiantePortalEstudianteProgramasIdRoute,
}

const PortalEstudianteRouteRouteWithChildren =
  PortalEstudianteRouteRoute._addFileChildren(
    PortalEstudianteRouteRouteChildren,
  )

interface ApiPublicSolicitudPagoTransporteRouteChildren {
  ApiPublicSolicitudPagoTransporteIdRoute: typeof ApiPublicSolicitudPagoTransporteIdRoute
}

const ApiPublicSolicitudPagoTransporteRouteChildren: ApiPublicSolicitudPagoTransporteRouteChildren =
  {
    ApiPublicSolicitudPagoTransporteIdRoute:
      ApiPublicSolicitudPagoTransporteIdRoute,
  }

const ApiPublicSolicitudPagoTransporteRouteWithChildren =
  ApiPublicSolicitudPagoTransporteRoute._addFileChildren(
    ApiPublicSolicitudPagoTransporteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  PortalEstudianteRouteRoute: PortalEstudianteRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SolicitudPagoTransporteRoute: SolicitudPagoTransporteRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCatalogoViajesTransporteRoute:
    ApiPublicCatalogoViajesTransporteRoute,
  ApiPublicSolicitudPagoTransporteRoute:
    ApiPublicSolicitudPagoTransporteRouteWithChildren,
  ImprimirSolicitudPagoIdRoute: ImprimirSolicitudPagoIdRoute,
  ApiPublicReciboPagoIdRoute: ApiPublicReciboPagoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
