/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotoRouteImport } from './routes/_authenticated/copiloto'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedTransportesIndexRouteImport } from './routes/_authenticated/transportes.index'
import { Route as AuthenticatedSolicitudesIndexRouteImport } from './routes/_authenticated/solicitudes.index'
import { Route as AuthenticatedPermisosIndexRouteImport } from './routes/_authenticated/permisos.index'
import { Route as AuthenticatedExpedientesIndexRouteImport } from './routes/_authenticated/expedientes.index'
import { Route as AuthenticatedTransportesNuevoRouteImport } from './routes/_authenticated/transportes.nuevo'
import { Route as AuthenticatedTransportesDashboardRouteImport } from './routes/_authenticated/transportes.dashboard'
import { Route as AuthenticatedTransportesIdRouteImport } from './routes/_authenticated/transportes.$id'
import { Route as AuthenticatedSolicitudesOcrRouteImport } from './routes/_authenticated/solicitudes.ocr'
import { Route as AuthenticatedSolicitudesNuevaRouteImport } from './routes/_authenticated/solicitudes.nueva'
import { Route as AuthenticatedSolicitudesIdRouteImport } from './routes/_authenticated/solicitudes.$id'
import { Route as AuthenticatedPermisosNuevoRouteImport } from './routes/_authenticated/permisos.nuevo'
import { Route as AuthenticatedPermisosIdRouteImport } from './routes/_authenticated/permisos.$id'
import { Route as AuthenticatedExpedientesPapeleraRouteImport } from './routes/_authenticated/expedientes.papelera'
import { Route as AuthenticatedExpedientesNuevoRouteImport } from './routes/_authenticated/expedientes.nuevo'
import { Route as AuthenticatedExpedientesIdRouteImport } from './routes/_authenticated/expedientes.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminCatalogosRouteImport } from './routes/_authenticated/admin.catalogos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotoRoute = AuthenticatedCopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportesIndexRoute =
  AuthenticatedTransportesIndexRouteImport.update({
    id: '/transportes/',
    path: '/transportes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesIndexRoute =
  AuthenticatedSolicitudesIndexRouteImport.update({
    id: '/solicitudes/',
    path: '/solicitudes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosIndexRoute =
  AuthenticatedPermisosIndexRouteImport.update({
    id: '/permisos/',
    path: '/permisos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesIndexRoute =
  AuthenticatedExpedientesIndexRouteImport.update({
    id: '/expedientes/',
    path: '/expedientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportesNuevoRoute =
  AuthenticatedTransportesNuevoRouteImport.update({
    id: '/transportes/nuevo',
    path: '/transportes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportesDashboardRoute =
  AuthenticatedTransportesDashboardRouteImport.update({
    id: '/transportes/dashboard',
    path: '/transportes/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransportesIdRoute =
  AuthenticatedTransportesIdRouteImport.update({
    id: '/transportes/$id',
    path: '/transportes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesOcrRoute =
  AuthenticatedSolicitudesOcrRouteImport.update({
    id: '/solicitudes/ocr',
    path: '/solicitudes/ocr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesNuevaRoute =
  AuthenticatedSolicitudesNuevaRouteImport.update({
    id: '/solicitudes/nueva',
    path: '/solicitudes/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitudesIdRoute =
  AuthenticatedSolicitudesIdRouteImport.update({
    id: '/solicitudes/$id',
    path: '/solicitudes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosNuevoRoute =
  AuthenticatedPermisosNuevoRouteImport.update({
    id: '/permisos/nuevo',
    path: '/permisos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPermisosIdRoute = AuthenticatedPermisosIdRouteImport.update({
  id: '/permisos/$id',
  path: '/permisos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpedientesPapeleraRoute =
  AuthenticatedExpedientesPapeleraRouteImport.update({
    id: '/expedientes/papelera',
    path: '/expedientes/papelera',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesNuevoRoute =
  AuthenticatedExpedientesNuevoRouteImport.update({
    id: '/expedientes/nuevo',
    path: '/expedientes/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpedientesIdRoute =
  AuthenticatedExpedientesIdRouteImport.update({
    id: '/expedientes/$id',
    path: '/expedientes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/admin/configuracion',
    path: '/admin/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCatalogosRoute =
  AuthenticatedAdminCatalogosRouteImport.update({
    id: '/admin/catalogos',
    path: '/admin/catalogos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/expedientes/': typeof AuthenticatedExpedientesIndexRoute
  '/permisos/': typeof AuthenticatedPermisosIndexRoute
  '/solicitudes/': typeof AuthenticatedSolicitudesIndexRoute
  '/transportes/': typeof AuthenticatedTransportesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/copiloto': typeof AuthenticatedCopilotoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/expedientes': typeof AuthenticatedExpedientesIndexRoute
  '/permisos': typeof AuthenticatedPermisosIndexRoute
  '/solicitudes': typeof AuthenticatedSolicitudesIndexRoute
  '/transportes': typeof AuthenticatedTransportesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/copiloto': typeof AuthenticatedCopilotoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/admin/catalogos': typeof AuthenticatedAdminCatalogosRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/expedientes/$id': typeof AuthenticatedExpedientesIdRoute
  '/_authenticated/expedientes/nuevo': typeof AuthenticatedExpedientesNuevoRoute
  '/_authenticated/expedientes/papelera': typeof AuthenticatedExpedientesPapeleraRoute
  '/_authenticated/permisos/$id': typeof AuthenticatedPermisosIdRoute
  '/_authenticated/permisos/nuevo': typeof AuthenticatedPermisosNuevoRoute
  '/_authenticated/solicitudes/$id': typeof AuthenticatedSolicitudesIdRoute
  '/_authenticated/solicitudes/nueva': typeof AuthenticatedSolicitudesNuevaRoute
  '/_authenticated/solicitudes/ocr': typeof AuthenticatedSolicitudesOcrRoute
  '/_authenticated/transportes/$id': typeof AuthenticatedTransportesIdRoute
  '/_authenticated/transportes/dashboard': typeof AuthenticatedTransportesDashboardRoute
  '/_authenticated/transportes/nuevo': typeof AuthenticatedTransportesNuevoRoute
  '/_authenticated/expedientes/': typeof AuthenticatedExpedientesIndexRoute
  '/_authenticated/permisos/': typeof AuthenticatedPermisosIndexRoute
  '/_authenticated/solicitudes/': typeof AuthenticatedSolicitudesIndexRoute
  '/_authenticated/transportes/': typeof AuthenticatedTransportesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/copiloto'
    | '/dashboard'
    | '/reportes'
    | '/admin/catalogos'
    | '/admin/configuracion'
    | '/admin/usuarios'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/expedientes/papelera'
    | '/permisos/$id'
    | '/permisos/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes/ocr'
    | '/transportes/$id'
    | '/transportes/dashboard'
    | '/transportes/nuevo'
    | '/expedientes/'
    | '/permisos/'
    | '/solicitudes/'
    | '/transportes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/copiloto'
    | '/dashboard'
    | '/reportes'
    | '/admin/catalogos'
    | '/admin/configuracion'
    | '/admin/usuarios'
    | '/expedientes/$id'
    | '/expedientes/nuevo'
    | '/expedientes/papelera'
    | '/permisos/$id'
    | '/permisos/nuevo'
    | '/solicitudes/$id'
    | '/solicitudes/nueva'
    | '/solicitudes/ocr'
    | '/transportes/$id'
    | '/transportes/dashboard'
    | '/transportes/nuevo'
    | '/expedientes'
    | '/permisos'
    | '/solicitudes'
    | '/transportes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/copiloto'
    | '/_authenticated/dashboard'
    | '/_authenticated/reportes'
    | '/_authenticated/admin/catalogos'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/expedientes/$id'
    | '/_authenticated/expedientes/nuevo'
    | '/_authenticated/expedientes/papelera'
    | '/_authenticated/permisos/$id'
    | '/_authenticated/permisos/nuevo'
    | '/_authenticated/solicitudes/$id'
    | '/_authenticated/solicitudes/nueva'
    | '/_authenticated/solicitudes/ocr'
    | '/_authenticated/transportes/$id'
    | '/_authenticated/transportes/dashboard'
    | '/_authenticated/transportes/nuevo'
    | '/_authenticated/expedientes/'
    | '/_authenticated/permisos/'
    | '/_authenticated/solicitudes/'
    | '/_authenticated/transportes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copiloto': {
      id: '/_authenticated/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof AuthenticatedCopilotoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/': {
      id: '/_authenticated/transportes/'
      path: '/transportes'
      fullPath: '/transportes/'
      preLoaderRoute: typeof AuthenticatedTransportesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/': {
      id: '/_authenticated/solicitudes/'
      path: '/solicitudes'
      fullPath: '/solicitudes/'
      preLoaderRoute: typeof AuthenticatedSolicitudesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/': {
      id: '/_authenticated/permisos/'
      path: '/permisos'
      fullPath: '/permisos/'
      preLoaderRoute: typeof AuthenticatedPermisosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/': {
      id: '/_authenticated/expedientes/'
      path: '/expedientes'
      fullPath: '/expedientes/'
      preLoaderRoute: typeof AuthenticatedExpedientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/nuevo': {
      id: '/_authenticated/transportes/nuevo'
      path: '/transportes/nuevo'
      fullPath: '/transportes/nuevo'
      preLoaderRoute: typeof AuthenticatedTransportesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/dashboard': {
      id: '/_authenticated/transportes/dashboard'
      path: '/transportes/dashboard'
      fullPath: '/transportes/dashboard'
      preLoaderRoute: typeof AuthenticatedTransportesDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transportes/$id': {
      id: '/_authenticated/transportes/$id'
      path: '/transportes/$id'
      fullPath: '/transportes/$id'
      preLoaderRoute: typeof AuthenticatedTransportesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/ocr': {
      id: '/_authenticated/solicitudes/ocr'
      path: '/solicitudes/ocr'
      fullPath: '/solicitudes/ocr'
      preLoaderRoute: typeof AuthenticatedSolicitudesOcrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/nueva': {
      id: '/_authenticated/solicitudes/nueva'
      path: '/solicitudes/nueva'
      fullPath: '/solicitudes/nueva'
      preLoaderRoute: typeof AuthenticatedSolicitudesNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitudes/$id': {
      id: '/_authenticated/solicitudes/$id'
      path: '/solicitudes/$id'
      fullPath: '/solicitudes/$id'
      preLoaderRoute: typeof AuthenticatedSolicitudesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/nuevo': {
      id: '/_authenticated/permisos/nuevo'
      path: '/permisos/nuevo'
      fullPath: '/permisos/nuevo'
      preLoaderRoute: typeof AuthenticatedPermisosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permisos/$id': {
      id: '/_authenticated/permisos/$id'
      path: '/permisos/$id'
      fullPath: '/permisos/$id'
      preLoaderRoute: typeof AuthenticatedPermisosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/papelera': {
      id: '/_authenticated/expedientes/papelera'
      path: '/expedientes/papelera'
      fullPath: '/expedientes/papelera'
      preLoaderRoute: typeof AuthenticatedExpedientesPapeleraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/nuevo': {
      id: '/_authenticated/expedientes/nuevo'
      path: '/expedientes/nuevo'
      fullPath: '/expedientes/nuevo'
      preLoaderRoute: typeof AuthenticatedExpedientesNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expedientes/$id': {
      id: '/_authenticated/expedientes/$id'
      path: '/expedientes/$id'
      fullPath: '/expedientes/$id'
      preLoaderRoute: typeof AuthenticatedExpedientesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogos': {
      id: '/_authenticated/admin/catalogos'
      path: '/admin/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AuthenticatedAdminCatalogosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCopilotoRoute: typeof AuthenticatedCopilotoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedAdminCatalogosRoute: typeof AuthenticatedAdminCatalogosRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedExpedientesIdRoute: typeof AuthenticatedExpedientesIdRoute
  AuthenticatedExpedientesNuevoRoute: typeof AuthenticatedExpedientesNuevoRoute
  AuthenticatedExpedientesPapeleraRoute: typeof AuthenticatedExpedientesPapeleraRoute
  AuthenticatedPermisosIdRoute: typeof AuthenticatedPermisosIdRoute
  AuthenticatedPermisosNuevoRoute: typeof AuthenticatedPermisosNuevoRoute
  AuthenticatedSolicitudesIdRoute: typeof AuthenticatedSolicitudesIdRoute
  AuthenticatedSolicitudesNuevaRoute: typeof AuthenticatedSolicitudesNuevaRoute
  AuthenticatedSolicitudesOcrRoute: typeof AuthenticatedSolicitudesOcrRoute
  AuthenticatedTransportesIdRoute: typeof AuthenticatedTransportesIdRoute
  AuthenticatedTransportesDashboardRoute: typeof AuthenticatedTransportesDashboardRoute
  AuthenticatedTransportesNuevoRoute: typeof AuthenticatedTransportesNuevoRoute
  AuthenticatedExpedientesIndexRoute: typeof AuthenticatedExpedientesIndexRoute
  AuthenticatedPermisosIndexRoute: typeof AuthenticatedPermisosIndexRoute
  AuthenticatedSolicitudesIndexRoute: typeof AuthenticatedSolicitudesIndexRoute
  AuthenticatedTransportesIndexRoute: typeof AuthenticatedTransportesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCopilotoRoute: AuthenticatedCopilotoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedAdminCatalogosRoute: AuthenticatedAdminCatalogosRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedExpedientesIdRoute: AuthenticatedExpedientesIdRoute,
  AuthenticatedExpedientesNuevoRoute: AuthenticatedExpedientesNuevoRoute,
  AuthenticatedExpedientesPapeleraRoute: AuthenticatedExpedientesPapeleraRoute,
  AuthenticatedPermisosIdRoute: AuthenticatedPermisosIdRoute,
  AuthenticatedPermisosNuevoRoute: AuthenticatedPermisosNuevoRoute,
  AuthenticatedSolicitudesIdRoute: AuthenticatedSolicitudesIdRoute,
  AuthenticatedSolicitudesNuevaRoute: AuthenticatedSolicitudesNuevaRoute,
  AuthenticatedSolicitudesOcrRoute: AuthenticatedSolicitudesOcrRoute,
  AuthenticatedTransportesIdRoute: AuthenticatedTransportesIdRoute,
  AuthenticatedTransportesDashboardRoute:
    AuthenticatedTransportesDashboardRoute,
  AuthenticatedTransportesNuevoRoute: AuthenticatedTransportesNuevoRoute,
  AuthenticatedExpedientesIndexRoute: AuthenticatedExpedientesIndexRoute,
  AuthenticatedPermisosIndexRoute: AuthenticatedPermisosIndexRoute,
  AuthenticatedSolicitudesIndexRoute: AuthenticatedSolicitudesIndexRoute,
  AuthenticatedTransportesIndexRoute: AuthenticatedTransportesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
